[system]
hostname = "genix"
use = ["-systemd", "elogind"]

[system.identity]
name = "Genix"
pretty_name = "Genix"
id = "genix"
id_like = "gentoo"
version = "0.1"
version_id = "0.1"
home_url = "https://genix.hoi-hoi33666.workers.dev/"
logo = "genix"
ansi_color = "38;2;192;132;184"
bug_report_url = "https://github.com/zubbledew6/genix/issues"
support_url = "https://github.com/zubbledew6/genix"

[system.portage]
accept_keywords = "amd64"
makeopts = "-j8"
features = "parallel-fetch"
binhost = "https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64"
binary = false
lfs = false

# these land in make.conf as-is
[system.portage.vars]
COMMON_FLAGS = "-O2 -pipe"
CFLAGS = "${COMMON_FLAGS}"
CXXFLAGS = "${COMMON_FLAGS}"
CHOST = "x86_64-pc-linux-gnu"
GRUB_PLATFORMS = "efi-64 pc"
ACCEPT_LICENSE = "* -@EULA"

[packages]
want = [
  "app-admin/sudo",
  "app-editors/nano",
  "app-editors/vim",
  "net-misc/dhcpcd",
  "net-misc/openssh",
  "net-wireless/iwd",
  "sys-boot/efibootmgr",
  "sys-boot/grub",
  "sys-fs/btrfs-progs",
  "sys-kernel/dracut",
  "sys-kernel/gentoo-kernel-bin",
  "sys-kernel/linux-firmware",
]

[packages.use]
"sys-kernel/installkernel" = ["dracut"]

# per-package autounmask -> /etc/portage/package.accept_keywords
# list, string, or bare "" (accept ~arch of the current arch)
[packages.keywords]
# "app-editors/vim" = ["~amd64"]
# "=dev-lang/rust-1.80.0" = "~amd64"

[services]
enable = ["iwd", "dhcpcd", "sshd"]

[system.boot]
enabled = true
backend = "grub"
subvol_prefix = "@genix-"
default_subvol = "@"
